### ISSUE TITLE
Error during loading a model

### ISSUE THREAD

**Issue by muminoff** [karolzak/keras-unet#18]
There is a model which was created using Jupyter notebook with filename `20200528-model-3.h5`. Now a new different notebook is created to load and test the model. But, model loading gets failed.

Here is the code:
```python
import tensorflow as tf
model_filename = '20200528-model-3.h5'
model = tf.keras.models.load_model(model_filename)
```

And error:
```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-20-11211a1508b6> in <module>
      1 model_filename = '20200528-model-3.h5'
----> 2 model = tf.keras.models.load_model(model_filename)

~/unetnew/env/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/save.py in load_model(filepath, custom_objects, compile)
    144   if (h5py is not None and (
    145       isinstance(filepath, h5py.File) or h5py.is_hdf5(filepath))):
--> 146     return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
    147 
    148   if isinstance(filepath, six.string_types):

~/unetnew/env/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/hdf5_format.py in load_model_from_hdf5(filepath, custom_objects, compile)
    182       # Compile model.
    183       model.compile(**saving_utils.compile_args_from_training_config(
--> 184           training_config, custom_objects))
    185 
    186       # Set optimizer weights.

~/unetnew/env/lib/python3.7/site-packages/tensorflow_core/python/training/tracking/base.py in _method_wrapper(self, *args, **kwargs)
    455     self._self_setattr_tracking = False  # pylint: disable=protected-access
    456     try:
--> 457       result = method(self, *args, **kwargs)
    458     finally:
    459       self._self_setattr_tracking = previous_value  # pylint: disable=protected-access

~/unetnew/env/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py in compile(self, optimizer, loss, metrics, loss_weights, sample_weight_mode, weighted_metrics, target_tensors, distribute, **kwargs)
    427     with K.get_graph().as_default():
    428       # Save all metric attributes per output of the model.
--> 429       self._cache_output_metric_attributes(metrics, weighted_metrics)
    430 
    431       # Set metric attributes on model.

~/unetnew/env/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py in _cache_output_metric_attributes(self, metrics, weighted_metrics)
   1840         output_shapes.append(output.shape.as_list())
   1841     self._per_output_metrics = training_utils.collect_per_output_metric_info(
-> 1842         metrics, self.output_names, output_shapes, self.loss_functions)
   1843     self._per_output_weighted_metrics = (
   1844         training_utils.collect_per_output_metric_info(

~/unetnew/env/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_utils.py in collect_per_output_metric_info(metrics, output_names, output_shapes, loss_fns, is_weighted)
    880       metric_name = get_metric_name(metric, is_weighted)
    881       metric_fn = get_metric_function(
--> 882           metric, output_shape=output_shapes[i], loss_fn=loss_fns[i])
    883 
    884       # If the metric function is not stateful, we create a stateful version.

~/unetnew/env/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_utils.py in get_metric_function(metric, output_shape, loss_fn)
   1105   """
   1106   if metric not in ['accuracy', 'acc', 'crossentropy', 'ce']:
-> 1107     return metrics_module.get(metric)
   1108 
   1109   is_sparse_categorical_crossentropy = (

~/unetnew/env/lib/python3.7/site-packages/tensorflow_core/python/keras/metrics.py in get(identifier)
   3062     return deserialize(identifier)
   3063   elif isinstance(identifier, six.string_types):
-> 3064     return deserialize(str(identifier))
   3065   elif callable(identifier):
   3066     return identifier

~/unetnew/env/lib/python3.7/site-packages/tensorflow_core/python/keras/metrics.py in deserialize(config, custom_objects)
   3054       module_objects=globals(),
   3055       custom_objects=custom_objects,
-> 3056       printable_module_name='metric function')
   3057 
   3058 

~/unetnew/env/lib/python3.7/site-packages/tensorflow_core/python/keras/utils/generic_utils.py in deserialize_keras_object(identifier, module_objects, custom_objects, printable_module_name)
    320       obj = module_objects.get(object_name)
    321       if obj is None:
--> 322         raise ValueError('Unknown ' + printable_module_name + ':' + object_name)
    323     # Classes passed by name are instantiated with no args, functions are
    324     # returned as-is.

ValueError: Unknown metric function:iou
```

This version loads the model but prediction output consists zero values:
```python
from keras_unet.models import custom_unet
model_filename = '20200528-model-3.h5'
model = custom_unet(
    input_shape,
    filters=64,
    use_batch_norm=True,
    dropout=0.01,
    dropout_change_per_layer=0.0,
    num_layers=4
)
model.load_weights(model_filename)
```

**Comment by karolzak** [comment]
@muminoff it's TF/Keras related issue.
Since you used a custom metric in your saved model (`iou`) and TF/Keras is not serializing custom objects when saving a model - you need to add something like this:

```python
import tensorflow as tf
from keras_unet.metrics import iou

model_filename = '20200528-model-3.h5'
model = tf.keras.models.load_model(
	model_filename,
	custom_objects={
		"iou": iou,
		}
)
```

**Comment by muminoff** [comment]
@karolzak Thank you. But how about `tflite_convert` utility? How can I use a custom metric function?

**Comment by karolzak** [comment]
I'm not 100% sure but I would assume that you need to [convert the binary](https://www.tensorflow.org/lite/convert/cmdline_examples) first and then while loading the model in python do it with "custom_objects" param. Have you tried that?

**Comment by muminoff** [comment]
Can you be more specific, please? I need to convert H5 model to TFLite. `tflite_convert` command fails.

```sh
    return [_deserialize_nested_config(deserialize_fn, obj) for obj in config]
  File "/home/user/unetnew/env/lib/python3.7/site-packages/tensorflow/python/keras/saving/saving_utils.py", line 262, in <listcomp>
    return [_deserialize_nested_config(deserialize_fn, obj) for obj in config]
  File "/home/user/unetnew/env/lib/python3.7/site-packages/tensorflow/python/keras/saving/saving_utils.py", line 255, in _deserialize_nested_config
    return deserialize_fn(config)
  File "/home/user/unetnew/env/lib/python3.7/site-packages/tensorflow/python/keras/saving/saving_utils.py", line 285, in _deserialize_metric
    return metrics_module.deserialize(metric_config)
  File "/home/user/unetnew/env/lib/python3.7/site-packages/tensorflow/python/keras/metrics.py", line 3349, in deserialize
    printable_module_name='metric function')
  File "/home/user/unetnew/env/lib/python3.7/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 392, in deserialize_keras_object
    raise ValueError('Unknown ' + printable_module_name + ':' + object_name)
ValueError: Unknown metric function:iou
(env) (base) user@thinkmachine:~/unetnew/tflite-model-improvement$ tflite_convert --keras_model_file 20200530-model-3.h5 --output_file foobar.tflite
```

I am using this command:
```sh
$ tflite_convert --keras_model_file 20200530-model-3.h5 --output_file foobar.tflite
```

**Comment by muminoff** [comment]
`tflite_convert` help menu has no custom metric option to use.

**Comment by muminoff** [comment]
All I need is to convert the model to the TFLite format. The method you mentioned earlier works fine. But that one is the H5 model. Now I need to convert it to TFLite format.

**Comment by muminoff** [comment]
This code:
```python
import tensorflow as tf
from keras_unet.metrics import iou, iou_thresholded

model_filename = '20200530-model-3.h5'
model = tf.keras.models.load_model(
	model_filename,
	custom_objects={
		"iou": iou,
                "iou_thresholded": iou_thresholded,
		}
)
converter = tf.lite.TFLiteConverter.from_keras_model(model)

converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.allow_custom_ops = True  # tried to comment this line but no success
converter.experimental_new_converter = True  # tried to comment this line but no success
converter.experimental_new_quantizer =  True  # tried to comment this line but no success

tfmodel = converter.convert()
open(f"{model_filename}.tflite" , "wb") .write(tfmodel)

print(model_filename)
```

also fails
```python
---------------------------------------------------------------------------
ConverterError                            Traceback (most recent call last)
<ipython-input-27-94e19846aeab> in <module>
      6 # converter.experimental_new_quantizer =  True
      7 
----> 8 tfmodel = converter.convert()
      9 open(f"{model_filename}.tflite" , "wb") .write(tfmodel)
     10 

~/unetnew/env/lib/python3.7/site-packages/tensorflow/lite/python/lite.py in convert(self)
    516         input_tensors=input_tensors,
    517         output_tensors=output_tensors,
--> 518         **converter_kwargs)
    519 
    520     if self._is_calibration_quantize():

~/unetnew/env/lib/python3.7/site-packages/tensorflow/lite/python/convert.py in toco_convert_impl(input_data, input_tensors, output_tensors, enable_mlir_converter, *args, **kwargs)
    494       input_data.SerializeToString(),
    495       debug_info_str=debug_info_str,
--> 496       enable_mlir_converter=enable_mlir_converter)
    497   return data
    498 

~/unetnew/env/lib/python3.7/site-packages/tensorflow/lite/python/convert.py in toco_convert_protos(model_flags_str, toco_flags_str, input_data_str, debug_info_str, enable_mlir_converter)
    225       stdout = _try_convert_to_unicode(stdout)
    226       stderr = _try_convert_to_unicode(stderr)
--> 227       raise ConverterError("See console for info.\n%s\n%s\n" % (stdout, stderr))
    228   finally:
    229     # Must manually cleanup files.

ConverterError: See console for info.
2020-06-01 15:33:24.224409: W tensorflow/compiler/mlir/lite/python/graphdef_to_tfl_flatbuffer.cc:144] Ignored output_format.
2020-06-01 15:33:24.224465: W tensorflow/compiler/mlir/lite/python/graphdef_to_tfl_flatbuffer.cc:147] Ignored drop_control_dependency.
2020-06-01 15:33:24.586299: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2020-06-01 15:33:24.628801: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2100000000 Hz
2020-06-01 15:33:24.636289: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7f7cc0000b20 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-06-01 15:33:24.636348: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-06-01 15:33:24.642673: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-06-01 15:33:25.471832: W tensorflow/compiler/xla/service/platform_util.cc:210] unable to create StreamExecutor for CUDA:0: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_OUT_OF_MEMORY: out of memory; total memory reported: 11554717696
2020-06-01 15:33:25.475584: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7f7bac000b20 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-06-01 15:33:25.475651: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce RTX 2080 Ti, Compute Capability 7.5
2020-06-01 15:33:25.475672: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (1): GeForce RTX 2080 Ti, Compute Capability 7.5
2020-06-01 15:33:25.475688: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (2): GeForce RTX 2080 Ti, Compute Capability 7.5
2020-06-01 15:33:25.475753: I tensorflow/compiler/jit/xla_gpu_device.cc:161] Ignoring visible XLA_GPU_JIT device. Device number is 0, reason: Invalid argument: device CUDA:0 not supported by XLA service
2020-06-01 15:33:25.655648: F tensorflow/stream_executor/lib/statusor.cc:34] Attempting to fetch value instead of handling error Internal: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_OUT_OF_MEMORY: out of memory; total memory reported: 11554717696
Fatal Python error: Aborted

Current thread 0x00007f7e96305740 (most recent call first):
  File "/home/user/unetnew/env/lib/python3.7/site-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 56 in execute
  File "/home/user/unetnew/env/lib/python3.7/site-packages/absl/app.py", line 250 in _run_main
  File "/home/user/unetnew/env/lib/python3.7/site-packages/absl/app.py", line 299 in run
  File "/home/user/unetnew/env/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 40 in run
  File "/home/user/unetnew/env/lib/python3.7/site-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 93 in main
  File "/home/user/unetnew/env/bin/toco_from_protos", line 8 in <module>
Aborted (core dumped)
```

**Comment by karolzak** [comment]
Did a bit of research and found this reference in TF docs: [https://www.tensorflow.org/api_docs/python/tf/compat/v1/lite/TFLiteConverter](https://www.tensorflow.org/api_docs/python/tf/compat/v1/lite/TFLiteConverter)

And I haven't tried it but if I'm correct your code should look somewhat like below:

```python

import tensorflow as tf
from keras_unet.metrics import iou, iou_thresholded

model_filename = '20200530-model-3.h5'
# model = tf.keras.models.load_model(
# 	model_filename,
# 	custom_objects={
# 		"iou": iou,
#                 "iou_thresholded": iou_thresholded,
# 		}
# )
converter = tf.compat.v1.lite.TFLiteConverter.from_keras_model_file(
	model_filename,
	custom_objects={
		"iou": iou,
		"iou_thresholded": iou_thresholded,
	}
)

# converter.optimizations = [tf.lite.Optimize.DEFAULT]
# converter.allow_custom_ops = True  # tried to comment this line but no success
# converter.experimental_new_converter = True  # tried to comment this line but no success
# converter.experimental_new_quantizer =  True  # tried to comment this line but no success

tfmodel = converter.convert()
open(f"{model_filename}.tflite", "wb").write(tfmodel)

print(model_filename)
```

**Comment by muminoff** [comment]
@karolzak tried your suggestion. TFLite model gets created but prediction output includes only zero values.

**Comment by karolzak** [comment]
@muminoff I assume that it works fine when loaded with TF and only returns zero values on TFLite? (for the same inputs). Sorry, I don't know what causes that, but I don't think it's related to `keras-unet`. Best bet is to search for similar issues with TFLite conversions from Keras - maybe there's some known issue related to this.
