### ISSUE TITLE
Trying to use Satellite net for 3 channel rgb images

### ISSUE THREAD

**Issue by shubham-scisar** [karolzak/keras-unet#34]
I am utilising 3 channel rgb images and 1 channel mask images for training. So, how can I utilise them to train of satellite unet as I can see in the notebooks that the image is grayscale and mask also is of one channel. Should I make the mask also 3 channel ?Please suggest the solution.

**Comment by karolzak** [comment]
Hi @shubhamsharma1609 
It doesn't really matter if you're using 1-channel, 3-channel or 20-channels as an input. You can have any number of channels in your input image and at the same time your output mask can be of any different number of channels.
Number of channels in the output mask defines how many classes are you trying to recognize with your model and is defined by `num_classes` param in `satellite_unet` function.
Your input shape on the other hand is defined by `input_shape` param of `satellite_unet` function and should look something like this `(height, width, num_channels)`.

Hope that helps

**Comment by shubham-scisar** [comment]
I am facing this issue while using the 3 channel training image and single channel mask :

```
import numpy as np
import matplotlib.pyplot as plt
#%matplotlib inline
import glob
import os
import sys
from PIL import Image
from skimage.transform import resize


masks = glob.glob("U:\\ALL\\masks_indb_255\\*.jpg")
orgs = glob.glob("U:\\train_indb\\*.png")


imgs_list = []
masks_list = []
for image, mask in zip(orgs, masks):
    imgs_list.append(np.array(Image.open(image)))
    
    im =np.array(Image.open(mask)) 
    #imm=np.dstack([im,im,im])
    #width, height = im.size   # Get dimensions

    #left = (width - 388)/2
    #top = (height - 388)/2
    #right = (width + 388)/2
    #bottom = (height + 388)/2

    #im_cropped = im.crop((left, top, right, bottom))
    masks_list.append(im)

imgs_np = np.asarray(imgs_list)
masks_np = np.asarray(masks_list)


print(imgs_np.shape, masks_np.shape)


from keras_unet.utils import plot_imgs

plot_imgs(org_imgs=imgs_np, mask_imgs=masks_np, nm_img_to_plot=10, figsize=6)

print(imgs_np.max(), masks_np.max())

x = np.asarray(imgs_np, dtype=np.float32)/255
y = np.asarray(masks_np, dtype=np.float32)/255


from sklearn.model_selection import train_test_split

x_train, x_val, y_train, y_val = train_test_split(x, y, test_size=0.5, random_state=0)

print("x_train: ", x_train.shape)
print("y_train: ", y_train.shape)
print("x_val: ", x_val.shape)
print("y_val: ", y_val.shape) 
 

from keras_unet.utils import get_augmented

train_gen = get_augmented(
    x_train, y_train, batch_size=30,
    data_gen_args = dict(
        rotation_range=15.,
        width_shift_range=0.05,
        height_shift_range=0.05,
        shear_range=50,
        zoom_range=0.2,
        horizontal_flip=True,
        vertical_flip=True,
        fill_mode='constant'
    )) 
 
```
Got this error :
```
Traceback (most recent call last):

  File "<ipython-input-62-5b10d6cd4c26>", line 23, in <module>
    fill_mode='constant'

  File "c:\users\shubham\anaconda3\envs\kerasunet\lib\site-packages\keras_unet\utils.py", line 54, in get_augmented
    Y_datagen.fit(Y_train, augment=True, seed=seed)

  File "C:\Users\SHUBHAM\AppData\Roaming\Python\Python37\site-packages\keras_preprocessing\image\image_data_generator.py", line 936, in fit
    'Got array with shape: ' + str(x.shape))

ValueError: Input to `.fit()` should have rank 4. Got array with shape: (70, 512, 512)
```

I am using 141 images for training and each is of size 512*512.So train test split has changed it to 71 validation images and 70 train images.

**Comment by shubhamsharma1609** [comment]
Also, can I change the size to 256*256 and train.

**Comment by karolzak** [comment]
This error is in fact related to your masks shape.
```
ValueError: Input to `.fit()` should have rank 4. Got array with shape: (70, 512, 512)
```
Your `y_train` is of rank 3 shape: `(70, 512, 512)` but it should be of rank 4 (include num_channels) like this `(70, 512, 512, 1)`.
So to fix your code you need to expand dims of your `y_train` like this:
```
y_train = np.expand_dims(y_train, axis=-1)
```
Do it before passing it into `get_augmented` function

**Comment by shubham-scisar** [comment]
Ok. I reshaped y to `y = y.reshape(y.shape[0], y.shape[1], y.shape[2], 1)` before augmenting.

**Comment by shubham-scisar** [comment]
I trained the model using satellite_unet and in prediction images ..I am getting complete black images. not able to make out what is going wrong. This is my code.

```
import numpy as np
import matplotlib.pyplot as plt
#%matplotlib inline
import glob
import os
import sys
from PIL import Image
from skimage.transform import resize


masks = glob.glob("U:\\ALL\\masks_indb_255\\*.jpg")
orgs = glob.glob("U:\\train_indb\\*.png")


imgs_list = []
masks_list = []
for image, mask in zip(orgs, masks):
    imgs_list.append(np.array(Image.open(image)))#.convert('L')),(256,256)))#.resize((512,512))))
    
    im =np.array(Image.open(mask)) #resize(np.array(Image.open(mask)),(256,256))
    #imm=np.dstack([im,im,im])
    #width, height = im.size   # Get dimensions

    #left = (width - 388)/2
    #top = (height - 388)/2
    #right = (width + 388)/2
    #bottom = (height + 388)/2

    #im_cropped = im.crop((left, top, right, bottom))
    masks_list.append(im)

imgs_np = np.asarray(imgs_list)
masks_np = np.asarray(masks_list)


print(imgs_np.shape, masks_np.shape)


from keras_unet.utils import plot_imgs

plot_imgs(org_imgs=imgs_np, mask_imgs=masks_np, nm_img_to_plot=10, figsize=6)

print(imgs_np.max(), masks_np.max())




x = np.asarray(imgs_np, dtype=np.float32)/255
y = np.asarray(masks_np, dtype=np.float32)/255
 
 
print(x.max(), y.max()) 

y = y.reshape(y.shape[0], y.shape[1], y.shape[2], 1)
print(x.shape, y.shape)

# x = x.reshape(x.shape[0], x.shape[1], x.shape[2], 1)
# print(x.shape, y.shape) 
 


from sklearn.model_selection import train_test_split

x_train, x_val, y_train, y_val = train_test_split(x, y, test_size=0.5, random_state=0)

print("x_train: ", x_train.shape)
print("y_train: ", y_train.shape)
print("x_val: ", x_val.shape)
print("y_val: ", y_val.shape) 
 

from keras_unet.utils import get_augmented

train_gen = get_augmented(
    x_train, y_train, batch_size=10,
    data_gen_args = dict(
        rotation_range=15.,
        width_shift_range=0.05,
        height_shift_range=0.05,
        shear_range=50,
        zoom_range=0.2,
        horizontal_flip=True,
        vertical_flip=True,
        fill_mode='constant'
    )) 
 
sample_batch = next(train_gen)
xx, yy = sample_batch
print(xx.shape, yy.shape)


from keras_unet.utils import plot_imgs

plot_imgs(org_imgs=xx, mask_imgs=yy, nm_img_to_plot=2, figsize=6)


from keras_unet.models import satellite_unet

input_shape = x_train[0].shape

model = satellite_unet(
    input_shape,
    #use_batch_norm=False,
    num_classes=1,
    #filters=64,
    #dropout=0.2,
    output_activation='relu',
    num_layers=4
)

from keras.callbacks import ModelCheckpoint


model_filename = 'U:\\model_v0.h5'
callback_checkpoint = ModelCheckpoint(
    model_filename, 
    verbose=1, 
    monitor='val_loss', 
    save_best_only=True,
)


from keras.optimizers import Adam, SGD
from keras_unet.metrics import iou, iou_thresholded
from keras_unet.losses import jaccard_distance

model.compile(
    #optimizer=Adam(), 
    optimizer=SGD(lr=0.01, momentum=0.99),
    loss='binary_crossentropy',
    #loss=jaccard_distance,
    metrics=[iou, iou_thresholded]
)




history = model.fit_generator(
    train_gen,
    steps_per_epoch=5,
    epochs=2,
    
    validation_data=(x_val, y_val),
    callbacks=[callback_checkpoint]
)



model.load_weights(model_filename)
y_pred = model.predict(x_val)


from keras_unet.utils import plot_imgs

plot_imgs(org_imgs=x_val, mask_imgs=y_val, pred_imgs=y_pred, nm_img_to_plot=9)
```

I have just one class.

**Comment by karolzak** [comment]
Well, there might be a lot of different issues. I don't know what your images and masks look like and how hard it is for the model to learn anything.
Dont expect results right away. I would start from training for longer than just 2 `epochs` and monitor `loss` value over epochs. If loss value is not decreasing then something is wrong.
Did you inspect your images before and after the augmentations? Do they look ok?

**Comment by shubham-scisar** [comment]
I am using tensorflow cpu for training...and here the batch size is small which is 10.The resultant images :
![snip_unet](https://user-images.githubusercontent.com/11288303/94008031-f0473200-fdbf-11ea-9449-2f507dd96b72.PNG)

The images after augmentation are pefect.

**Comment by karolzak** [comment]
How good is your labelling? From the 2 examples you showed it seems like there's nothing easily distinguishable from the background where your masks are labelled.
The general rule of thumb is: if human eye can't tell the difference - deep learning model definitely can't do it. In your case I can't tell what you're trying to recognize in those images (maybe they are just to small for me to tell).
My first opinion based on what you showed is that model simply can't learn (or its hard for it to learn) what you're trying to detect because it's not easily distinguishable from the other stuff in the image.
But again I would add more data, increase `steps_per_epoch` and train for longer than just 2 epochs. Monitor the loss value in the process and let it run for a while - then check the results and see if it's learning anything.

**Comment by shubham-scisar** [comment]
Ok.When,I am trying to train on cpu, I am getting memory error.I will increase the batch size and steps per epoch  and run this on gpu to get some meaningful output.

**Comment by shubham-scisar** [comment]
I tried to run the above mentioned code in AWS sagemaker instance having keras =2.3.1 and tensorflow=2.0.2. But I am getting the following error after running this :

```
history = model.fit_generator(
    train_gen,
    steps_per_epoch=5,
    epochs=3,
    
    validation_data=(x_val, y_val),
    callbacks=[callback_checkpoint]
)
```

The error :

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-23-a832c74cfe86> in <module>
      5 
      6     validation_data=(x_val, y_val),
----> 7     callbacks=[callback_checkpoint]
      8 )

~/anaconda3/envs/amazonei_tensorflow2_p36/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py in fit_generator(self, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, validation_freq, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
   1295         shuffle=shuffle,
   1296         initial_epoch=initial_epoch,
-> 1297         steps_name='steps_per_epoch')
   1298 
   1299   def evaluate_generator(self,

~/anaconda3/envs/amazonei_tensorflow2_p36/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_generator.py in model_iteration(model, data, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, validation_freq, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch, mode, batch_size, steps_name, **kwargs)
    142       batch_size=batch_size,
    143       epochs=epochs - initial_epoch,
--> 144       shuffle=shuffle)
    145 
    146   do_validation = validation_data is not None

~/anaconda3/envs/amazonei_tensorflow2_p36/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_generator.py in convert_to_generator_like(data, batch_size, steps_per_epoch, epochs, shuffle)
    475 
    476   # Create generator from NumPy or EagerTensor Input.
--> 477   num_samples = int(nest.flatten(data)[0].shape[0])
    478   if batch_size is None:
    479     raise ValueError(

AttributeError: 'zip' object has no attribute 'shape'
```
