### ISSUE TITLE
satellite_unet custom_objects: '<' not supported between instances of 'function' and 'str' 

### ISSUE THREAD

**Issue by parcodepie** [karolzak/keras-unet#47]
I'm trying to continue training model "satellite_unet" by loading weights. but got this issue when using custom_objects

here is the code 
`model = satellite_unet(
    input_shape,
)
callback_checkpoint = ModelCheckpoint(
    os.path.join(checkpoint_path, 'weights.{epoch:02d}.{val_loss:.4f}.hdf5'),
    verbose=1,
    monitor='val_loss',
    save_best_only=True
)
model.compile(
    optimizer=SGD(lr=0.01, momentum=0.99),
    loss='binary_crossentropy',
    metrics=[iou, iou_thresholded]
)

####### if checkpoints exist  get last_epoch ....

model = load_model(os.path.join(checkpoint_path, checkpoint_path_file), custom_objects={
        "iou": iou,
        "iou_thresholded": iou_thresholded,
    })
    history = model.fit(
        train_gen,
        steps_per_epoch=len(x_train),
        epochs=EPOCHS,
        validation_data=(x_val, y_val),
        callbacks=[callback_checkpoint],
        initial_epoch=last_epoch
    )`

**Comment by karolzak** [comment]
Hi @parcodepie 
Could you share more details on this issue? It's hard to understand what is the problem and it's impossible to replicate.

**Comment by parcodepie** [comment]
I'm using this [repo](https://github.com/sanpreet/Loading-saved-keras-model-and-continue-training-from-last-epoch/blob/master/load_saved_keras_model.py) to load last checkpoints if exists before so I could continue training 
here is the whole code. 
It works where there is no checkpoints before but when trying to load the last checkpoints the error thrown
Here is the whole code:


```
import numpy as np
import glob
from PIL import Image
from tensorflow.keras.optimizers import SGD
import os
from tensorflow.keras.models import load_model
from keras_net.keras_unet.metrics import iou, iou_thresholded
from keras_unet.models import satellite_unet
from keras_unet.utils import get_augmented, plot_segm_history
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras.callbacks import ModelCheckpoint

SAVED_MODEL = 'model_test.h5'
EPOCHS = 10
BATCH_SIZE = 6
CHECK_POINT = "cp-{epoch:04d}.ckpt"
images = glob.glob("/xx/train/*.png")
masks = glob.glob("/xx/*.png")
checkpoint_path = 'weight'

images_list = []
masks_list = []
for image, mask in zip(images, masks):
    images_list.append(np.array(Image.open(image).resize((384, 384))))
    masks_list.append(np.array(Image.open(mask).resize((384, 384))))

images_np = np.asarray(images_list)
masks_np = np.asarray(masks_list)

x = np.asarray(images_np, dtype=np.float32) / 255
y = np.asarray(masks_np, dtype=np.float32) / 255

y = y.reshape(y.shape[0], y.shape[1], y.shape[2], 1)
print(x.shape, y.shape)

x_train, x_val, y_train, y_val = train_test_split(x, y, test_size=0.8, random_state=0)


train_gen = get_augmented(
    x_train, y_train,
    batch_size=BATCH_SIZE,
    data_gen_args=dict(
        rotation_range=5.,
        width_shift_range=0.05,
        height_shift_range=0.05,
        shear_range=40,
        zoom_range=0.2,
        horizontal_flip=True,
        vertical_flip=True,
        fill_mode='constant'
    ))

input_shape = x_train[0].shape
print("input_shape:", input_shape)
model = satellite_unet(
    input_shape,
)

callback_checkpoint = ModelCheckpoint(
    os.path.join(checkpoint_path, 'weights.{epoch:02d}.{val_loss:.4f}.hdf5'),
    verbose=1,
    monitor='val_loss',
    save_best_only=True
)

model.compile(
    optimizer=SGD(lr=0.01, momentum=0.99),
    loss='binary_crossentropy',
    metrics=[iou, iou_thresholded]
)


def checkpoint_function():
    # if there is no file being saved in the checkpoint path then routine will go to loop model.fit(X, y, epochs=150, batch_size=1, callbacks=[ckpt_callback])
    # this signifies that no file is saved in the checkpoint path and let us begin the training from the first epoch.
    if not os.listdir(checkpoint_path):
        return
    # this loop will fetch epochs number in a list
    files_int = list()
    for i in os.listdir(checkpoint_path):
        epoch = int(i.split('.')[1])
        files_int.append(epoch)
    # getting the maximum value for an epoch from the list
    # this is reference value and will help to find the file with that value
    max_value = max(files_int)
    # conditions are applied to find the file which has the maximum value of epoch
    # such file would be the last file where the training is stopped and we would like to resume the training from that point.
    for i in os.listdir(checkpoint_path):
        epoch = int(i.split('.')[1])
        if epoch > max_value:
            pass
        elif epoch < max_value:
            pass
        else:
            final_file = i
            # in the end we will get the epoch as well as file
    return final_file, max_value


checkpoint_path_file = checkpoint_function()

if checkpoint_path_file is not None:
    # Load model:
    checkpoint_path_file = checkpoint_function()[0]
    last_epoch = checkpoint_function()[1]

    model = load_model(os.path.join(checkpoint_path, checkpoint_path_file), custom_objects={
        "iou": iou,
        "iou_thresholded": iou_thresholded,
    })
     model.fit(
        train_gen,
        steps_per_epoch=len(x_train),
        epochs=EPOCHS,
        validation_data=(x_val, y_val),
        callbacks=[callback_checkpoint],
        initial_epoch=last_epoch
    )
           #   if there is no checkpoint_path_file it means no file is saved and hence model will be trained from scratch
          #   file is saved in form of .hdf5 extension
else:
     model.fit(
        train_gen,
        steps_per_epoch=len(x_train),
        epochs=EPOCHS,
        validation_data=(x_val, y_val),
        callbacks=[callback_checkpoint],
    )
```

**Comment by karolzak** [comment]
In one of your imports you have this line:
```from keras_net.keras_unet.metrics import iou, iou_thresholded```
I don't think it's correct. Please try changing it to the following:
```from keras_unet.metrics import iou, iou_thresholded```
let me know if that helped

**Comment by parcodepie** [comment]
Thanks @karolzak  but it's because I have two folders has the same name inside so the import is correct.(keras_net/keras_unet)
the project folder and your repo folder

I forgot to put the whole exception. Here it is

```
Epoch 4/10
Traceback (most recent call last):
  File "/home/x/Documents/projects/keras_net/re_train.py", line 125, in <module>
    history = model.fit(
  File "/home/x/anaconda3/envs/tensorflow/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 1100, in fit
    tmp_logs = self.train_function(iterator)
  File "/home/x/anaconda3/envs/tensorflow/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "/home/x/anaconda3/envs/tensorflow/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 871, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/home/x/anaconda3/envs/tensorflow/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 725, in _initialize
    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
  File "/home/x/anaconda3/envs/tensorflow/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2969, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/home/x/anaconda3/envs/tensorflow/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3361, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/x/anaconda3/envs/tensorflow/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3196, in _create_graph_function
    func_graph_module.func_graph_from_py_func(
  File "/home/x/anaconda3/envs/tensorflow/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 990, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/x/anaconda3/envs/tensorflow/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 634, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/home/x/anaconda3/envs/tensorflow/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 977, in wrapper
    raise e.ag_error_metadata.to_exception(e)
TypeError: in user code:

    /home/x/anaconda3/envs/tensorflow/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:805 train_function  *
        return step_function(self, iterator)
    /home/x/anaconda3/envs/tensorflow/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:795 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    /home/x/anaconda3/envs/tensorflow/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:1259 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /home/x/anaconda3/envs/tensorflow/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:2730 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /home/x/anaconda3/envs/tensorflow/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:3417 _call_for_each_replica
        return fn(*args, **kwargs)
    /home/x/anaconda3/envs/tensorflow/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:790 run_step  **
        with ops.control_dependencies(_minimum_control_deps(outputs)):
    /home/x/anaconda3/envs/tensorflow/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:2793 _minimum_control_deps
        outputs = nest.flatten(outputs, expand_composites=True)
    /home/x/anaconda3/envs/tensorflow/lib/python3.8/site-packages/tensorflow/python/util/nest.py:341 flatten
        return _pywrap_utils.Flatten(structure, expand_composites)

    TypeError: '<' not supported between instances of 'function' and 'str'

```

**Comment by parcodepie** [comment]
I think it works now after I changed the compile option for **False** and compile the model after loading it from the last checkpoints

```
 model = load_model(os.path.join(checkpoint_path, checkpoint_path_file), compile=False, custom_objects={
        "iou": iou,
        "iou_thresholded": iou_thresholded,
    })

 model.compile(
        optimizer=SGD(lr=0.01, momentum=0.99),
        loss='binary_crossentropy',
        metrics=[iou, iou_thresholded]
    )
```
It now continues training from the last checkpoints. But is there a way to make sure it works?

**Comment by karolzak** [comment]
No other option than just training it for a bit and running some predictions to see :)
